productionSlot: blue

microservice:
  name: api-gateway
  namespace: spring-petclinic
  replicaCount: 2
  current_environment_blue: prod
  current_environment_green: stage
  resources:
    limits:
      memory: 500Mi
      cpu: 300m
    requests:
      cpu: 300m
      memory: 500Mi
  livenessProbe:
    enabled: true
    initialDelaySeconds: 90
    periodSeconds: 5
  readinessProbe:
    enabled: true
    initialDelaySeconds: 15
  profile_env_blue: kubernetes
  profile_env_green: kubernetes-stage
  uri: api-gateway.spring-petclinic.svc.cluster.local
  image:
    repository_blue: j4ro123/spring-petclinic-api-gateway
    repository_green: j4ro123/spring-petclinic-api-gateway
    tag_blue: latest
    tag_green: latest
  containerPort: 8080
  service:
    type: ClusterIP
    port: 8080
