green:
  enabled: true

blue:
  enabled: true

productionSlot: blue
productionSlotConfig: blue

microservice:
  name: api-gateway
  namespace: spring-petclinic
  replicaCount: 1
  current_environment_blue: prod
  current_environment_green: stage
  resources:
    limits:
      memory: 1Gi
      cpu: 700m
    requests:
      cpu: 700m
      memory: 1Gi
  profile_env_blue: kubernetes
  profile_env_green: kubernetes-stage
  uri: api-gateway.spring-petclinic.svc.cluster.local
  image:
    repository_blue: j4ro123/spring-petclinic-api-gateway
    repository_green: j4ro123/spring-petclinic-api-gateway
    tag_blue: latest
    tag_green: latest
  containerPort: 8080
  service:
    type: ClusterIP
    port: 8080
