admin:
  ## Name of the secret. Can be templated.
  existingSecret: "grafana-secret"
  userKey: username
  passwordKey: password

resources:
  limits:
    cpu: 400m
    memory: 1Gi
  requests:
    cpu: 400m
    memory: 1Gi

namespaceOverride: "monitoring"
