green:
  enabled: true

blue:
  enabled: true

productionSlot: blue

database:
  uri_env_blue: mysql-prod.prod-db
  uri_env_green: mysql-stage.stage-db
  port: 3306
  username: root
  password:
    secret: db-password-secret
    key: password

microservice:
  name: visits-service
  namespace: spring-petclinic
  replicaCount: 1
  current_environment_blue: prod
  current_environment_green: stage
  resources:
    limits:
      memory: 1Gi
      cpu: 700m
    requests:
      cpu: 700m
      memory: 1Gi
  image:
    repository_blue: j4ro123/spring-petclinic-visits-service
    repository_green: j4ro123/spring-petclinic-visits-service
    tag_blue: latest
    tag_green: latest
  containerPort: 8080
  service:
    type: ClusterIP
    port: 8082
