version: "3"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    deploy:
      resources:
        limits:
          memory: 1000M
    environment:
      - MYSQL_ROOT_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - ./spring-petclinic-customers-service/src/main/resources/db/mysql/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./spring-petclinic-customers-service/src/main/resources/db/mysql/data.sql:/docker-entrypoint-initdb.d/2-data.sql

      - ./spring-petclinic-visits-service/src/main/resources/db/mysql/schema.sql:/docker-entrypoint-initdb.d/3-schema.sql
      - ./spring-petclinic-visits-service/src/main/resources/db/mysql/data.sql:/docker-entrypoint-initdb.d/4-data.sql

      - ./spring-petclinic-vets-service/src/main/resources/db/mysql/schema.sql:/docker-entrypoint-initdb.d/5-schema.sql
      - ./spring-petclinic-vets-service/src/main/resources/db/mysql/data.sql:/docker-entrypoint-initdb.d/6-data.sql

    ports:
      - 3306:3306
  config-server:
    image: j4ro123/spring-petclinic-config-server
    container_name: config-server
    mem_limit: 1000M
    ports:
      - 8888:8888
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  customers-service:
    image: j4ro123/spring-petclinic-customers-service
    container_name: customers-service
    mem_limit: 1000M
    depends_on:
      - config-server
    entrypoint:
      [
        "./dockerize",
        "-wait=tcp://config-server:8888",
        "-timeout=60s",
        "--",
        "java",
        "org.springframework.boot.loader.JarLauncher",
      ]
    environment:
      - SPRING_PROFILES_ACTIVE=docker, mysql
    ports:
      - 8081:8080

  visits-service:
    image: j4ro123/spring-petclinic-visits-service
    container_name: visits-service
    mem_limit: 1000M
    depends_on:
      - config-server
    entrypoint:
      [
        "./dockerize",
        "-wait=tcp://config-server:8888",
        "-timeout=60s",
        "--",
        "java",
        "org.springframework.boot.loader.JarLauncher",
      ]
    environment:
      - SPRING_PROFILES_ACTIVE=docker, mysql
    ports:
      - 8082:8080

  vets-service:
    image: j4ro123/spring-petclinic-vets-service
    container_name: vets-service
    mem_limit: 1000M
    depends_on:
      - config-server
    entrypoint:
      [
        "./dockerize",
        "-wait=tcp://config-server:8888",
        "-timeout=60s",
        "--",
        "java",
        "org.springframework.boot.loader.JarLauncher",
      ]
    environment:
      - SPRING_PROFILES_ACTIVE=docker, mysql
    ports:
      - 8083:8080

  api-gateway:
    image: j4ro123/spring-petclinic-api-gateway
    container_name: api-gateway
    mem_limit: 1000M
    depends_on:
      - config-server
    entrypoint:
      [
        "./dockerize",
        "-wait=tcp://config-server:8888",
        "-timeout=60s",
        "--",
        "java",
        "org.springframework.boot.loader.JarLauncher",
      ]
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8080:8080

  # tracing-server:
  #   image: openzipkin/zipkin
  #   container_name: tracing-server
  #   mem_limit: 1000M
  #   environment:
  #     - JAVA_OPTS=-XX:+UnlockExperimentalVMOptions -Djava.security.egd=file:/dev/./urandom
  #   ports:
  #     - 9411:9411

  ## Grafana / Prometheus

  # grafana-server:
  #   build: ./docker/grafana
  #   container_name: grafana-server
  #   mem_limit: 256M
  #   ports:
  #     - 3000:3000

  # prometheus-server:
  #   build: ./docker/prometheus
  #   container_name: prometheus-server
  #   mem_limit: 256M
  #   ports:
  #     - 9091:9090
