spring:
  application:
    name: vets-service
  config:
    import: optional:configserver:http://${CONFIG_SERVER_URL:config-server}:${CONFIG_SERVER_PORT:8888}
  cache:
    cache-names: vets
  profiles:
    active: production
---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://${CONFIG_SERVER_URL:config-server}:${CONFIG_SERVER_PORT:8888}
