{{- range $name, $svc := .Values.microservices }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
spec:
  replicas: {{ $svc.replicaCount }}
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      containers:
        - name: {{ $name }}
          image: "{{ $svc.image.repository }}:{{ $svc.image.tag }}"
          resources:
            limits:
              memory: "700Mi"
            requests:
              memory: "700Mi"
          ports:
            - containerPort: {{ $svc.containerPort }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
            - name: MANAGEMENT_METRICS_EXPORT_WAVEFRONT_URI
              value: proxy://wavefront-proxy.default.svc.cluster.local:2878
          {{- if or (eq $name "customers-service") (eq $name "visits-service") (eq $name "vets-service") }}
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql.default.svc.cluster.local:3306/petclinic
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                  secretKeyRef:
                    name: db-password-secret
                    key: password
          {{- end }}
{{- end }}
