productionSlot: blue

database:
  uri_env_blue: mysql-prod.prod-db
  uri_env_green: mysql-stage.stage-db
  port: 3306
  username: root
  password:
    secret: db-password-secret
    key: password

microservice:
  name: vets-service
  namespace: spring-petclinic
  replicaCount: 2
  current_environment_blue: prod
  current_environment_green: stage
  resources:
    limits:
      memory: 500Mi
      cpu: 300m
    requests:
      cpu: 300m
      memory: 500Mi
  livenessProbe:
    enabled: true
    initialDelaySeconds: 90
    periodSeconds: 5
  readinessProbe:
    enabled: true
    initialDelaySeconds: 15
  image:
    repository_blue: j4ro123/spring-petclinic-vets-service
    repository_green: j4ro123/spring-petclinic-vets-service
    tag_blue: latest
    tag_green: latest
  containerPort: 8080
  service:
    type: ClusterIP
    port: 8083
