green:
  enabled: false

blue:
  enabled: false

productionSlot: blue

database:
  uri: mysql.spring-petclinic.svc.cluster.local
  port: 3306
  username: root
  password:
    secret: db-password-secret
    key: password

microservice:
  name: customers-service
  namespace: spring-petclinic
  replicaCount: 2
  resources:
    limits:
      # memory: 1Gi
      memory: 800Mi
    requests:
      # memory: 1Gi
      memory: 800Mi

  uri: customers-service.spring-petclinic.svc.cluster.local
  image:
    repository_blue: j4ro123/spring-petclinic-customers-service
    repository_green: j4ro123/spring-petclinic-customers-service
    tag_blue: latest
    tag_green: latest
  containerPort: 8080
  service:
    type: ClusterIP
    port: 8081
