spring:
  application:
    name: discovery-server
  config:
    import: optional:configserver:http://${CONFIG_SERVER_URL:config-server}:${CONFIG_SERVER_PORT:8888}

# Avoid some debugging logs at startup
logging:
  level:
    org:
      springframework:
        boot: INFO
        web: INFO

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://${CONFIG_SERVER_URL:config-server}:${CONFIG_SERVER_PORT:8888}
