spring:
  application:
    name: customers-service
  config:
    import: optional:configserver:http://${CONFIG_SERVER_URL:config-server}:${CONFIG_SERVER_PORT:8888}
---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://${CONFIG_SERVER_URL:config-server}:${CONFIG_SERVER_PORT:8888}
