{{- range $name, $svc := .Values.microservices }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
      "helm.sh/hook": pre-install,pre-upgrade
      "helm.sh/hook-weight": "-1"
      "helm.sh/hook-delete-policy": before-hook-creation
  name: {{ $name }}
  labels:
    app: {{ $name }}
  namespace: {{ $svc.namespace }}
spec:
  replicas: {{ $svc.replicaCount }}
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      containers:
        - name: {{ $name }}
          image: "{{ $svc.image.repository }}:{{ $svc.image.tag }}"
          resources:
            limits:
              memory: "1Gi"
            requests:
              # cpu: 2000m
              memory: "1Gi"
          ports:
            - containerPort: {{ $svc.containerPort }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
            # - name: MANAGEMENT_METRICS_EXPORT_WAVEFRONT_URI
            #   value: proxy://wavefront-proxy.spring-petclinic.svc.cluster.local:2878
          {{- if or (eq $name "customers-service") (eq $name "visits-service") (eq $name "vets-service") }}
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql.spring-petclinic.svc.cluster.local:3306/petclinic
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                  secretKeyRef:
                    name: db-password-secret
                    key: password
          {{- end }}
{{- end }}
