{{- range $name, $svc := .Values.microservices }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": before-hook-creation
  name: {{ $name }}
  namespace: {{ $svc.namespace }}
spec:
  type: {{ $svc.service.type }}
  ports:
    - port: {{ $svc.service.port }}
      targetPort: {{ $svc.containerPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ $name }}
{{- end }}
