{{ if .Values.blue.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.microservice.name}}-blue
  labels:
    app: {{.Values.microservice.name}}
  namespace: {{.Values.microservice.namespace}}
spec:
  replicas: {{.Values.microservice.replicaCount}}
  selector:
    matchLabels:
      app: {{.Values.microservice.name}}
  template:
    metadata:
      labels:
        app: {{.Values.microservice.name}}
        slot: blue
    spec:
      containers:
        - name: {{.Values.microservice.name}}
          image: "{{ .Values.microservice.image.repository_blue }}:{{ .Values.microservice.image.tag_blue }}"
          resources:
            limits:
              memory: {{.Values.microservice.resources.limits.memory}}
            requests:
              memory: {{.Values.microservice.resources.requests.memory}}
          ports:
            - containerPort: {{.Values.microservice.containerPort}}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ if eq .Values.productionSlot "blue" }}kubernetes{{ else }}kubernetes-stage
{{ end }}