{{ if .Values.green.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.microservice.name}}-green-{{.Values.microservice.current_environment_green}}
  labels:
    app: {{.Values.microservice.name}}
  namespace: {{.Values.microservice.namespace}}
  annotations:
    # Annotation to specify which ConfigMap to watch for changes
    # Reloader will trigger a rolling update if this ConfigMap changes
    configmap.reloader.stakater.com/reload: "api-gateway-green-config"
spec:
  replicas: {{.Values.microservice.replicaCount}}
  selector:
    matchLabels:
      app: {{.Values.microservice.name}}
  template:
    metadata:
      labels:
        app: {{.Values.microservice.name}}
        slot: green
    spec:
      containers:
        - name: {{.Values.microservice.name}}
          image: "{{ .Values.microservice.image.repository_green }}:{{ .Values.microservice.image.tag_green }}"
          resources:
            limits:
              cpu: {{.Values.microservice.resources.limits.cpu}}
              memory: {{.Values.microservice.resources.limits.memory}}
            requests:
              cpu: {{.Values.microservice.resources.requests.cpu}}
              memory: {{.Values.microservice.resources.requests.memory}}
          ports:
            - containerPort: {{.Values.microservice.containerPort}}
          envFrom:
          - configMapRef:
              name: api-gateway-green-config
          # env:
          #   - name: SPRING_PROFILES_ACTIVE
          #     value: {{.Values.microservice.profile_env_green}}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.microservice.containerPort }}
            initialDelaySeconds: 90
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.microservice.containerPort }}
            initialDelaySeconds: 15
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]
{{ end }}