{{ if .Values.green.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.microservice.name}}-green
  labels:
    app: {{.Values.microservice.name}}
  namespace: {{.Values.microservice.namespace}}
spec:
  replicas: {{.Values.microservice.replicaCount}}
  selector:
    matchLabels:
      app: {{.Values.microservice.name}}
  template:
    metadata:
      labels:
        app: {{.Values.microservice.name}}
        slot: green
    spec:
      containers:
        - name: {{.Values.microservice.name}}
          image: "{{ .Values.microservice.image.repository }}:{{ .Values.microservice.image.tag }}"
          resources:
            limits:
              memory: {{.Values.microservice.resources.limits.memory}}
            requests:
              memory: {{.Values.microservice.resources.requests.memory}}
          ports:
            - containerPort: {{.Values.microservice.containerPort}}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
{{ end }}