{{ if .Values.blue.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.microservice.name}}-blue-{{.Values.microservice.current_environment_blue}}
  labels:
    app: {{.Values.microservice.name}}
  namespace: {{.Values.microservice.namespace}}
spec:
  replicas: {{.Values.microservice.replicaCount}}
  selector:
    matchLabels:
      app: {{.Values.microservice.name}}
  template:
    metadata:
      labels:
        app: {{.Values.microservice.name}}
        slot: blue
    spec:
      containers:
        - name: {{.Values.microservice.name}}
          image: "{{ .Values.microservice.image.repository_blue }}:{{ .Values.microservice.image.tag_blue }}"
          resources:
            limits:
              cpu: {{.Values.microservice.resources.limits.cpu}}
              memory: {{.Values.microservice.resources.limits.memory}}
            requests:
              cpu: {{.Values.microservice.resources.requests.cpu}}
              memory: {{.Values.microservice.resources.requests.memory}}
          ports:
            - containerPort: {{.Values.microservice.containerPort}}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{.Values.microservice.profile_env_blue}}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.microservice.containerPort }}
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.microservice.containerPort }}
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
{{ end }}